openapi: 3.1.0
info:
  title: Task Management API - Protected Task Endpoints
  description: RESTful API for managing user tasks with JWT authentication
  version: 2.0.0
  contact:
    name: Todo App Team

servers:
  - url: http://localhost:8000
    description: Development server (FastAPI backend)

paths:
  /api/tasks:
    get:
      summary: List all tasks for authenticated user
      description: Returns all tasks owned by the authenticated user, sorted by creation date (newest first)
      operationId: listTasks
      tags:
        - Tasks
      security:
        - bearerAuth: []
      parameters:
        - name: completed
          in: query
          description: Filter by completion status
          required: false
          schema:
            type: boolean
            example: false
        - name: limit
          in: query
          description: Maximum number of tasks to return
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 50
            example: 20
        - name: offset
          in: query
          description: Number of tasks to skip (for pagination)
          required: false
          schema:
            type: integer
            minimum: 0
            default: 0
            example: 0
      responses:
        '200':
          description: List of tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
        '401':
          $ref: '#/components/responses/Unauthorized'

    post:
      summary: Create a new task
      description: Creates a new task owned by the authenticated user
      operationId: createTask
      tags:
        - Tasks
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskCreate'
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'

  /api/tasks/{task_id}:
    get:
      summary: Get a specific task
      description: Returns a task by ID (only if owned by authenticated user)
      operationId: getTask
      tags:
        - Tasks
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/TaskId'
      responses:
        '200':
          description: Task details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'

    put:
      summary: Update a task
      description: Updates a task (only if owned by authenticated user)
      operationId: updateTask
      tags:
        - Tasks
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/TaskId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskUpdate'
      responses:
        '200':
          description: Task updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'

    delete:
      summary: Delete a task
      description: Deletes a task (only if owned by authenticated user)
      operationId: deleteTask
      tags:
        - Tasks
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/TaskId'
      responses:
        '204':
          description: Task deleted successfully
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'

components:
  schemas:
    Task:
      type: object
      required:
        - id
        - title
        - completed
        - user_id
        - created_at
        - updated_at
      properties:
        id:
          type: integer
          description: Unique task identifier
          example: 42
        title:
          type: string
          minLength: 1
          maxLength: 255
          description: Task title
          example: "Complete project documentation"
        description:
          type: string
          nullable: true
          maxLength: 10000
          description: Detailed task description
          example: "Write comprehensive API documentation with examples"
        completed:
          type: boolean
          description: Task completion status
          example: false
        user_id:
          type: integer
          description: ID of the user who owns this task
          example: 123
        created_at:
          type: string
          format: date-time
          description: Task creation timestamp
          example: "2026-02-07T12:00:00Z"
        updated_at:
          type: string
          format: date-time
          description: Last update timestamp
          example: "2026-02-07T14:30:00Z"

    TaskCreate:
      type: object
      required:
        - title
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 255
          description: Task title
          example: "Complete project documentation"
        description:
          type: string
          nullable: true
          maxLength: 10000
          description: Detailed task description
          example: "Write comprehensive API documentation with examples"
        completed:
          type: boolean
          default: false
          description: Initial completion status
          example: false

    TaskUpdate:
      type: object
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 255
          description: Updated task title
          example: "Complete project documentation"
        description:
          type: string
          nullable: true
          maxLength: 10000
          description: Updated task description
          example: "Write comprehensive API documentation with examples"
        completed:
          type: boolean
          description: Updated completion status
          example: true

    Error:
      type: object
      required:
        - detail
      properties:
        detail:
          type: string
          description: Error message
          example: "Task not found"

  parameters:
    TaskId:
      name: task_id
      in: path
      required: true
      description: Unique task identifier
      schema:
        type: integer
        example: 42

  responses:
    BadRequest:
      description: Invalid request data
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            detail: "Title must not be empty"

    Unauthorized:
      description: Missing or invalid authentication token
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            missingToken:
              value:
                detail: "Not authenticated"
            expiredToken:
              value:
                detail: "Token has expired"
            invalidToken:
              value:
                detail: "Invalid token"
      headers:
        WWW-Authenticate:
          description: Authentication scheme
          schema:
            type: string
            example: Bearer

    Forbidden:
      description: Authenticated but not authorized to access this resource
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            detail: "Not authorized to access this task"

    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            detail: "Task not found"

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token obtained from Better Auth `/api/auth/token` endpoint

security:
  - bearerAuth: []

tags:
  - name: Tasks
    description: Task management operations (all require authentication)
